---

- name: burp-server | unprivileged user
  tags:
    - user
  user:
    name: "{{ burp_user }}"
    shell: /bin/false
    home: "{{ burp_data_dir }}"
    system: yes

- name: burp-server | config
  tags:
    - config
  template:
    src: "{{ item.src }}.j2"
    dest: "{{ burp_conf_dir }}/{{ item.dest }}/{{ item.src }}"
    owner: "{{ burp_user }}"
    mode: "0400"
  loop:
    - { src: server.conf, dest: "" }
    - { src: dhfile.pem, dest: keys }
  notify: restart burp

- name: burp-server | directories
  tags:
    - dir
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ burp_user }}"
    group: "{{ burp_user }}"
    mode: "0750"
  loop:
    - "{{ burp_data_dir }}"
    - "{{ burp_pid_dir }}"
  notify: restart burp

- include_tasks: offsite_cron.yml
  when: not not burp_offsite

- name: burp-server | systemd service dir
  file:
    path: "{{ burp_systemd }}.d"
    state: directory

- name: burp-server | systemd service
  tags:
    - systemd
  template:
    src: "{{ item.src }}.j2"
    dest: "/etc/systemd/system/{{ item.dest }}/{{ item.src }}"
  loop:
    - { src: burp.service, dest: "{{ burp_systemd | dirname }}" }
    - { src: iptables.conf, dest: "{{ burp_systemd }}.d" }
  notify: 
    - daemon-reload
    - restart burp

- name: burp-server | service
  tags:
    - service
  service:
    name: burp
    state: started
    enabled: yes
