---

- name: burp-server | offsite_cron | script
  tags:
  - script
  template:
    src: offsite.j2
    dest: "{{ burp_conf_dir }}/offsite"
    owner: "{{ burp_user }}"
    group: "{{ burp_user }}"
    mode: "0750"

- name: burp-server | offsite_cron | cronjob
  tags:
  - cron
  cron:
    name: 'burp offsite storage cron'
    cron_file: burp_offsite
    user: root
    minute: "{{ 59 | random(seed=inventory_hostname) }}"
    hour: "3"
    job: "{{ burp_conf_dir }}/offsite"

